version: 2

project_name: fl

before:
  hooks:
    - go mod tidy

builds:
  - binary: fl
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/flowershow/publish/internal/config.Version={{ .Env.CLI_VERSION }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  name_template: "{{.Tag}}"
