name = "flowershow-markdown-worker"
main = "src/worker.js"
compatibility_date = "2024-03-18"
compatibility_flags = ["nodejs_compat", "rpc"]

[observability]
enabled = true
head_sampling_rate = 1

# PRODUCTION
[env.production.vars]
ENVIRONMENT = "production"
POSTHOG_HOST = "https://eu.i.posthog.com"

[env.production.triggers]
crons = ["0 3 * * *"]

[[env.production.queues.consumers]]
queue = "flowershow-markdown-queue"
max_batch_size = 10
max_batch_timeout = 1
max_retries = 3

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "flowershow-cloud"

[[env.production.workflows]]
binding = "PUBLISH_FINALIZER_WORKFLOW"
name = "flowershow-publish-finalizer-workflow"
class_name = "PublishFinalizerWorkflow"

[[env.production.workflows]]
binding = "GITHUB_SYNC_WORKFLOW"
name = "flowershow-github-sync-workflow"
class_name = "GitHubSyncWorkflow"

# STAGING
[env.staging.vars]
ENVIRONMENT = "staging"
POSTHOG_HOST = "https://eu.i.posthog.com"

[env.staging.triggers]
crons = ["0 3 * * *"]

[[env.staging.queues.consumers]]
queue = "flowershow-markdown-queue-staging"
max_batch_size = 10
max_batch_timeout = 1
max_retries = 3

[[env.staging.r2_buckets]]
binding = "BUCKET"
bucket_name = "flowershow-cloud-staging"

[[env.staging.workflows]]
binding = "PUBLISH_FINALIZER_WORKFLOW"
name = "flowershow-publish-finalizer-workflow-staging"
class_name = "PublishFinalizerWorkflow"

[[env.staging.workflows]]
binding = "GITHUB_SYNC_WORKFLOW"
name = "flowershow-github-sync-workflow-staging"
class_name = "GitHubSyncWorkflow"

# DEV
[env.dev]
port = 8787
local_protocol = "http"

[env.dev.vars]
ENVIRONMENT = "dev"

[[env.dev.queues.producers]]
binding = "FILE_PROCESSOR_QUEUE"
queue = "markdown-processing-queue-dev"

[[env.dev.queues.consumers]]
queue = "markdown-processing-queue-dev"
max_batch_size = 10
max_batch_timeout = 1
max_retries = 3

[[env.dev.workflows]]
binding = "PUBLISH_FINALIZER_WORKFLOW"
name = "flowershow-publish-finalizer-workflow-dev"
class_name = "PublishFinalizerWorkflow"

[[env.dev.workflows]]
binding = "GITHUB_SYNC_WORKFLOW"
name = "flowershow-github-sync-workflow-dev"
class_name = "GitHubSyncWorkflow"
