import {
  BlueskyIcon,
  DiscordIcon,
  FacebookIcon,
  GithubIcon,
  InstagramIcon,
  LinkedInIcon,
  MastodonIcon,
  PinterestIcon,
  RedditIcon,
  SpotifyIcon,
  SubstackIcon,
  TelegramIcon,
  ThreadsIcon,
  TikTokIcon,
  TwitterIcon,
  WhatsAppIcon,
  YouTubeIcon,
} from '@/components/icons';
import { SocialPlatform } from '@/components/types';
import { MailIcon } from 'lucide-react';

export const socialIcons: { [K in SocialPlatform]: React.FC<any> } = {
  bluesky: BlueskyIcon,
  bsky: BlueskyIcon,
  discord: DiscordIcon,
  mail: (props) => <MailIcon strokeWidth={2.5} {...props} />,
  facebook: FacebookIcon,
  github: GithubIcon,
  instagram: InstagramIcon,
  linkedin: LinkedInIcon,
  mastodon: MastodonIcon,
  pinterest: PinterestIcon,
  reddit: RedditIcon,
  spotify: SpotifyIcon,
  substack: SubstackIcon,
  telegram: TelegramIcon,
  threads: ThreadsIcon,
  tiktok: TikTokIcon,
  twitter: TwitterIcon,
  whatsapp: WhatsAppIcon,
  x: TwitterIcon,
  youtube: YouTubeIcon,
};
