import '@testing-library/jest-dom/vitest';
import { vi } from 'vitest';

vi.mock('@/env.mjs', () => ({
  env: {
    // Server env vars
    NEXTAUTH_URL: 'http://localhost:3000',
    POSTGRES_PRISMA_URL: 'postgresql://test:test@localhost:5432/test',
    POSTGRES_URL_NON_POOLING: 'postgresql://test:test@localhost:5432/test',
    NEXTAUTH_SECRET: 'test-secret',
    AUTH_GITHUB_SECRET: 'test-github-secret',
    AUTH_GOOGLE_ID: 'test-google-id',
    AUTH_GOOGLE_SECRET: 'test-google-secret',
    S3_ENDPOINT: 'https://s3.test.com',
    S3_ACCESS_KEY_ID: 'test-key-id',
    S3_SECRET_ACCESS_KEY: 'test-secret-key',
    S3_BUCKET_NAME: 'test-bucket',
    S3_REGION: 'auto',
    S3_FORCE_PATH_STYLE: false,
    GH_WEBHOOK_SECRET: 'test-webhook-secret',
    GH_WEBHOOK_URL: 'https://test.com/webhook',
    GITHUB_APP_ID: 'test-app-id',
    GITHUB_APP_SLUG: 'test-app-slug',
    GITHUB_APP_CLIENT_ID: 'test-client-id',
    GITHUB_APP_CLIENT_SECRET: 'test-client-secret',
    GITHUB_APP_WEBHOOK_SECRET: 'test-webhook-secret',
    GITHUB_APP_PRIVATE_KEY: 'test-private-key',
    GITHUB_TOKEN_ENCRYPTION_KEY: 'test-encryption-key',
    GTM_ID: 'GTM-TEST',
    BREVO_API_KEY: 'test-brevo-key',
    BREVO_CONTACT_LISTID: '1',
    TURNSTILE_SECRET_KEY: 'test-turnstile-secret',
    INNGEST_APP_ID: 'test-inngest-app',
    STRIPE_SECRET_KEY: 'sk_test_xxx',
    STRIPE_WEBHOOK_SECRET: 'whsec_test',
    TYPESENSE_ADMIN_API_KEY: 'test-typesense-key',
    SITE_ACCESS_JWT_SECRET: 'test-jwt-secret',
    ANONYMOUS_JWT_SECRET: 'test-anon-jwt-secret',
    // Client env vars
    NEXT_PUBLIC_AUTH_GITHUB_ID: 'test-github-id',
    NEXT_PUBLIC_ROOT_DOMAIN: 'test.localhost',
    NEXT_PUBLIC_CLOUD_DOMAIN: 'cloud.test.localhost',
    NEXT_PUBLIC_HOME_DOMAIN: 'test.localhost',
    NEXT_PUBLIC_VERCEL_DEPLOYMENT_SUFFIX: 'vercel.app',
    NEXT_PUBLIC_VERCEL_ENV: 'test',
    NEXT_PUBLIC_DNS_DOMAIN: 'dns.test.com',
    NEXT_PUBLIC_S3_BUCKET_DOMAIN: 's3.test.com',
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: 'test-site-key',
    NEXT_PUBLIC_TYPESENSE_CLIENT_API_KEY: 'test-client-key',
    NEXT_PUBLIC_TYPESENSE_HOST: 'localhost',
    NEXT_PUBLIC_TYPESENSE_PORT: '8108',
    NEXT_PUBLIC_TYPESENSE_PROTOCOL: 'http',
    NEXT_PUBLIC_POSTHOG_KEY: 'test-posthog-key',
    NEXT_PUBLIC_POSTHOG_HOST: 'https://app.posthog.com',
    NEXT_PUBLIC_STRIPE_PREMIUM_MONTHLY_PRICE_ID: 'price_monthly',
    NEXT_PUBLIC_STRIPE_PREMIUM_YEARLY_PRICE_ID: 'price_yearly',
  },
}));
